- name: Download Docker
  get_url: 
    url: https://get.docker.com
    dest: /tmp/installer.sh
    mode: 0755

- name: Install Docker
  shell: bash /tmp/installer.sh

- name: Add Apt signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add K8s repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install k8s packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

